# Generated by Django 5.2.17 on 2026-10-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='car_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='car_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='car_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
